name: counter_backend
description: Distributed Counter Backend using grpc
version: 1.0.0

environment:
  sdk: '>=2.18.1 <3.0.0'

dependencies: 
  grpc: ^3.1.0
  protobuf: ^2.1.0
  redis: ^3.1.0
  rxdart: ^0.27.7

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
